language: java
jdk:
- openjdk8
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv
  -in application.properties.enc -out application.properties -d
- chmod +x mvnw
